### ISSUE TITLE
Uncaught (in promise) NotFound: No such file or directory (os error 2) on tgz.compress

### ISSUE THREAD

**Issue by martin-braun** [deno-library/compress#13]
I have a Laravel project folder called `MY-PROJECT` that contains several files with deep folder structure: 

```
+ MY-PROJECT
| + app
| |- ...
| + bootstrap
| |- ...
| + database
| | + factories
| | |- UserFactory.php
| | + migrations
| | |- ...
| |- .gitignore
| + public
| |- ...
| + resources
| |- ...
| + routes
| |- ...
| + scripts
| |- ...
| + storage
| |- ...
| + tests
| |- ...
|- .editorconfig
|- .env
|- .env.example
|- .gitignore
|- .rnd
|- artisan
|- composer.json
|- composer.lock
|- my.cnf
|- my.cnf.example
|- phpunit.xml
|- README.md
|- server.php
|- webpack.mix.js
```

I try to compress it like this: 

```js
await tgz.compress('/Users/user/MY-PROJECT', '/Users/user/MY-PROJECT.tar.gz', {
	excludeSrc: true // doesn't matter if true or false
})
```

and it fails: 

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), stat '/Users/user/MY-PROJECT/database/my.cnf.example'
        const stat = await Deno.stat(filePath);
                     ^
    at async Object.stat (deno:runtime/js/30_fs.js:228:17)
    at async appendFolder (https://deno.land/x/compress@v0.4.1/tar/mod.ts:41:22)
    at async Module.compress (https://deno.land/x/compress@v0.4.1/tar/mod.ts:70:7)
    at async Module.compress (https://deno.land/x/compress@v0.4.1/tgz/mod.ts:27:3)
```

The recursion seems not to work right as of now.

```sh
$% deno --version
deno 1.19.3 (release, x86_64-apple-darwin)
v8 9.9.115.8
typescript 4.5.2
```

compress v0.4.1

**Comment by martin-braun** [comment]
Pretty sure this issue was introduced by the fix of #8 and I cannot rollback, because of #9.

**Comment by fuxingZhang** [comment]
you are right

**Comment by fuxingZhang** [comment]
@martin-braun

**Comment by fuxingZhang** [comment]
I have fixed the bug

**Comment by fuxingZhang** [comment]
I have fixed the bug. you can try v0.4.2

**Comment by fuxingZhang** [comment]
If you have a good idea, **I am very happy to merge your pull request.**

**Comment by fuxingZhang** [comment]
@martin-braun

**Comment by martin-braun** [comment]
Thanks I can only test this a bit later, I will get back to you, thanks for your patience.

**Comment by martin-braun** [comment]
It works now, thanks a lot. :)
